language: python
python:
#  - "2.6" # unsupported due to reportlab, which is needed for PDF downloads, not supporting 2.6.
  - "2.7"

env:
  - DJANGO=1.7

install:
  - "pip install coveralls"
  - "pip install -r requirements.txt"
  - "pip install ."
  - pip install -q Django==$DJANGO --use-mirrors #Currently only runs on django1.7 due to tasty-api

# command to run tests
script:
  - coverage run --branch --source=aristotle_glossary manage.py test
after_success:
  - coveralls
