language: python
python:
  - "2.7"

env:
  - DJANGO=1.8
  - DJANGO=1.10

install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements.test.txt"
  - "pip install ."
  - pip install -q Django==$DJANGO --use-mirrors

# command to run tests
script:
  - coverage run --branch --source=aristotle_glossary manage.py test
after_success:
  - coveralls
